---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-nose-tests
spec:
  workspaces:
    - name: shared-workspace
  steps:
    - name: run-tests
      image: python:3.9-slim
      workingDir: /workspace/shared-workspace
      script: |
        #!/bin/sh
        echo "Installing dependencies..."
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install nose
        echo "Running tests..."
        nosetests --with-spec --spec-color
